### ISSUE TITLE
CommonJS require does not seem to work

### ISSUE THREAD

**Issue by JamesMGreene** [dzek69/express-abort#4]
Usage:

```js
const { default: createAbortMiddleware } = require('express-abort/dist')
```

Error:

```
$ node server.js
/Users/jamesmgreene/dev/docs-internal/node_modules/better-custom-error/src/index.js:219
export default createError;
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/jamesmgreene/dev/docs-internal/node_modules/express-abort/dist/index.js:8:49)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

Looks like the CommonJS compilation fails when it tries to load `better-custom-error`'s ESM-type code? 🤷🏻‍♂️ 😬

**Comment by dzek69** [comment]
Hello,
Thanks for report. This is one of the libraries I've created using my old library template which has a commonjs support bug and forgot about it.

I've updated the library, please bump version to 3.0.0. There is no need to require with `/dist` now and there is no default export, just named exports. See updated example in README.

I hope that helps, please let me know, thanks!

**Comment by JamesMGreene** [comment]
Thanks!
